# Generated by Django 3.2.5 on 2021-07-26 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eshopapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='technical_specification',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
